version: '3.8'
services:
  productdb:
    image: postgres:13
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - productdb

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - product-service

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service